
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


group: !include groups.yaml
automation: !include automations.yaml
# script: !include scripts.yaml
scene: !include scenes.yaml
lovelace: !include lovelace_config.yaml
frontend:
  themes: !include_dir_merge_named themes
homeassistant:
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /config/ #Necesario para detectar el tamaño de la DB
    - /config/backups #Necesario para detectar si se ha creado el backup
    - /config/recordings


recorder:
  exclude:
    entities: !include extra_config/exclude_entities.yaml

history:
  exclude:
    entities: !include extra_config/exclude_entities.yaml


#Integración con Google Home
google_assistant:
  project_id: !secret project_id_google_home
  service_account: !include google_home.json
  report_state: true


# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'es'


# Permite Wake on lan
wake_on_lan:


binary_sensor:
    #Días laborables
  - platform: workday
    name: Día laborable
    country: ES
    province: !secret province
    add_holidays:





















